import { lazy } from "react";
import { Building2, Users, Truck, User } from "lucide-react";
import { RouteDefinition } from "../../../app/routes/types";

// Domain-driven route definitions
export const directoryRoutes: RouteDefinition[] = [
  {
    path: "/empresas",
    component: lazy(() => import("@/features/entities/company/pages/CompanyPage")),
    title: "Empresas",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "companies:view",
    domain: "company",
    entityType: "empresa",
    action: "list",
    breadcrumb: "Empresas"
  },
  {
    path: "/empresas/new",
    component: lazy(() => import("@/features/entities/company/pages/CompanyDetailsPage")),
    title: "Nueva Empresa",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "companies:create",
    domain: "company",
    entityType: "empresa",
    action: "create",
    breadcrumb: "Nueva Empresa",
    hideInMenu: true
  },
  {
    path: "/empresas/:id",
    component: lazy(() => import("@/features/entities/company/pages/CompanyDetailsPage")),
    title: "Detalles de Empresa",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "companies:view",
    domain: "company",
    entityType: "empresa",
    action: "detail",
    breadcrumb: "Detalles",
    hideInMenu: true
  },
  {
    path: "/empresas/:companyId/catalogos",
    component: lazy(() => import("@/features/entities/company/pages/CompanyCatalogsPage")),
    title: "Catálogos de Empresa",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "companies:view",
    domain: "company",
    entityType: "catalogo",
    action: "list",
    breadcrumb: "Catálogos",
    hideInMenu: true
  },
  {
    path: "/clientes",
    component: lazy(() => import("@/features/entities/client/pages/ClientPage")),
    title: "Clientes",
    icon: <Users className="h-5 w-5" />,
    requireAuth: true,
    permission: "clients:view",
    domain: "client",
    entityType: "cliente",
    action: "list",
    breadcrumb: "Clientes"
  },
  {
    path: "/clientes/:id",
    component: lazy(() => import("@/features/entities/client/pages/ClientDetailsPage")),
    title: "Detalle de Cliente",
    icon: <Users className="h-5 w-5" />,
    requireAuth: true,
    permission: "clients:view",
    domain: "client",
    entityType: "cliente",
    action: "detail",
    breadcrumb: "Detalle",
    hideInMenu: true
  },
  {
    path: "/clientes/new",
    component: lazy(() => import("@/features/entities/client/pages/ClientEditPage")),
    title: "Nuevo Cliente",
    icon: <Users className="h-5 w-5" />,
    requireAuth: true,
    permission: "clients:create",
    domain: "client",
    entityType: "cliente",
    action: "create",
    breadcrumb: "Nuevo",
    hideInMenu: true
  },
  {
    path: "/clientes/:id/edit",
    component: lazy(() => import("@/features/entities/client/pages/ClientEditPage")),
    title: "Editar Cliente",
    icon: <Users className="h-5 w-5" />,
    requireAuth: true,
    permission: "clients:edit",
    domain: "client",
    entityType: "cliente",
    action: "edit",
    breadcrumb: "Editar",
    hideInMenu: true
  },
  {
    path: "/proveedores",
    component: lazy(() => import("@/features/entities/supplier/pages/SupplierPage")),
    title: "Proveedores",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "suppliers:view",
    domain: "supplier",
    entityType: "proveedor",
    action: "list",
    breadcrumb: "Proveedores"
  },
  {
    path: "/proveedores/:id",
    component: lazy(() => import("@/features/entities/supplier/pages/SupplierDetailsPage")),
    title: "Detalle de Proveedor",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "suppliers:view",
    domain: "supplier",
    entityType: "proveedor",
    action: "detail",
    breadcrumb: "Detalle",
    hideInMenu: true
  },
  {
    path: "/proveedores/new",
    component: lazy(() => import("@/features/entities/supplier/pages/SupplierEditPage")),
    title: "Nuevo Proveedor",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "suppliers:create",
    domain: "supplier",
    entityType: "proveedor",
    action: "create",
    breadcrumb: "Nuevo",
    hideInMenu: true
  },
  {
    path: "/proveedores/:id/edit",
    component: lazy(() => import("@/features/entities/supplier/pages/SupplierEditPage")),
    title: "Editar Proveedor",
    icon: <Building2 className="h-5 w-5" />,
    requireAuth: true,
    permission: "suppliers:edit",
    domain: "supplier",
    entityType: "proveedor",
    action: "edit",
    breadcrumb: "Editar",
    hideInMenu: true
  },
  {
    path: "/transportes",
    component: lazy(() => import("@/features/entities/transport/pages/TransportPage")),
    title: "Transportes",
    icon: <Truck className="h-5 w-5" />,
    requireAuth: true,
    permission: "transports:view",
    domain: "transport",
    entityType: "transporte",
    action: "list",
    breadcrumb: "Transportes"
  },
  {
    path: "/transportes/:id",
    component: lazy(() => import("@/features/entities/transport/pages/TransportDetailsPage")),
    title: "Detalle de Transporte",
    icon: <Truck className="h-5 w-5" />,
    requireAuth: true,
    permission: "transports:view",
    domain: "transport",
    entityType: "transporte",
    action: "detail",
    breadcrumb: "Detalle",
    hideInMenu: true
  },
  {
    path: "/transportes/new",
    component: lazy(() => import("@/features/entities/transport/pages/TransportEditPage")),
    title: "Nuevo Transporte",
    icon: <Truck className="h-5 w-5" />,
    requireAuth: true,
    permission: "transports:create",
    domain: "transport",
    entityType: "transporte",
    action: "create",
    breadcrumb: "Nuevo",
    hideInMenu: true
  },
  {
    path: "/transportes/:id/edit",
    component: lazy(() => import("@/features/entities/transport/pages/TransportEditPage")),
    title: "Editar Transporte",
    icon: <Truck className="h-5 w-5" />,
    requireAuth: true,
    permission: "transports:edit",
    domain: "transport",
    entityType: "transporte",
    action: "edit",
    breadcrumb: "Editar",
    hideInMenu: true
  },
  {
    path: "/usuarios",
    component: lazy(() => import("@/features/user/pages/UserPage")),
    title: "Usuarios",
    icon: <User className="h-5 w-5" />,
    requireAuth: true,
    permission: "users:view",
    domain: "admin",
    entityType: "usuario",
    action: "list",
    breadcrumb: "Usuarios"
  }
];
