
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekxmysomkrmwhlxkwhvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreG15c29ta3Jtd2hseGt3aHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDU2MDMsImV4cCI6MjA1ODUyMTYwM30.5kxkRIY4EFE4jRa8W-1pwIKH82crcCBOadE-rnYGFGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Check if Supabase connection is working
 * @returns Promise<boolean> true if connection is working, false otherwise
 */
export async function checkSupabaseConnection(): Promise<boolean> {
  try {
    // Try to get server time as a basic connectivity test
    const { data, error } = await supabase.rpc('get_server_time');
    
    // If there's no RPC function, fall back to a simple query
    if (error) {
      const { error: tableError } = await supabase
        .from('users')
        .select('count', { count: 'exact', head: true });
      
      return !tableError;
    }
    
    return !!data;
  } catch (error) {
    console.error('Error checking Supabase connection:', error);
    return false;
  }
}

/**
 * Check if a table exists and is accessible
 * @param table Table name to check
 * @returns Promise<{exists: boolean, error?: string}> result of check
 */
export async function checkTableAccess(table: string): Promise<{exists: boolean, error?: string}> {
  try {
    // Try to query the table
    let result;
    
    // Handle the specific case for 'usuarios' table since it's not in the Database type
    if (table === 'usuarios') {
      // For the 'usuarios' table (custom name), use a raw query to check
      const { data, error } = await supabase.rpc('check_table_access', { table_name: 'users' });
      
      if (error) {
        // Fall back to a simple count query
        result = await supabase.from('users').select('count', { count: 'exact', head: true });
      } else {
        return { exists: !!data, error: data ? undefined : 'Table not accessible' };
      }
    } else {
      // For other tables, attempt a standard query
      result = await supabase.from(table as any).select('count', { count: 'exact', head: true });
    }
    
    if (result?.error) {
      return {
        exists: false,
        error: result.error.message || `Error accessing table: ${table}`
      };
    }
    
    return { exists: true };
  } catch (error: any) {
    console.error(`Error checking table access for ${table}:`, error);
    return {
      exists: false,
      error: error?.message || `Unknown error accessing table: ${table}`
    };
  }
}
