// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekxmysomkrmwhlxkwhvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVreG15c29ta3Jtd2hseGt3aHZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NDU2MDMsImV4cCI6MjA1ODUyMTYwM30.5kxkRIY4EFE4jRa8W-1pwIKH82crcCBOadE-rnYGFGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);